name = "savoraapp-github"
main = "worker.js"
compatibility_date = "2025-01-01"

# Cloudflare account
account_id = "de262f98ef47a3a6c986661d98a0c217"

# Environment variables
[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://savoraapp.com"
ADMIN_USER = "admin"

# KV Namespace
[[kv_namespaces]]
binding = "VERIFICATION_KV"
id = "aace89c748a8424f8dd3393a7bf19f52"
